version: 3
services:
  main_website:
    image: docker.io/nginxinc/nginx-unprivileged
    restart: unless-stopped
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
      - './public:/opt/data'
      - './preview:/opt/previewdata'

networks:
  default:
    external: true
    name: nginx-proxy-network
